# 1207版本
server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

hmdp:
  jwt:
    #    # 设置jwt签名加密时使用的秘钥
    #    admin-secret-key: itcast
    #    # 设置jwt过期时间
    #    admin-ttl: 7200000
    #    # 设置前端传递过来的令牌名称
    #    admin-token-name: token
    user-secret-key: ThisIsA32BytesLongSecretKeyForHS256
    user-ttl: 7200000
    user-token-name: authorization
